merge-key: "fyre-dev/masdemo1/inst1"
ibm_mas_suite_configs:
  - mas_config_name: "inst1-bas-system"
    mas_config_chart: ibm-mas-bas-config
    mas_config_scope: system
    mas_workspace_id: inst1ws1
    mas_application_id:
    mas_config_kind: "bascfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    dro_api_token: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/dro#dro_api_token>
    dro_endpoint_url: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/dro#dro_url>
    dro_contact:
      email: user@example.com
      first_name: Joe
      last_name: Blogs
    dro_ca:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
        ZXNzLW9wZXJhdG9yQDE3MDcxNDkwNjQwHhcNMjQwMjA1MTYwNDI0WhcNMjYwMjA0
        MTYwNDI1WjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3MDcxNDkwNjQw
        ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpaz/JX2StBDEFopdBfalm
        ee5zxlAaRTl5JAFa17iWMICpL9z3C8l22DcGahTHCkjzMexl8CtB4HM2cQHPiBnX
        No7gmKwCHJ2MgRCf4KpMMS1DnpojDkuv2rQupIq4Y+Qt4DQ5e/TlV1BP24Oxm1d2
        hfIb9AOMGa5S+erj3zK1MtlAbpXYivz4mFDsIpcZ0LVwBfQnHqbDV6+MSpfB3J5F
        MOoOu//SxJ6tQqQpYBA7BGYKiULDxaV4C46mGJd73SOGZFIgHSM8kC+uAxO0PGGm
        wF82dwxnwS1VLhYBNumSnPmBckeDkZ//H/xe6fp2XY9bi70P3nYtiC5/7azOrcp3
        AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
        A1UdDgQWBBQRhiasCu/kNg2H/2kPhgwAsHgVbTANBgkqhkiG9w0BAQsFAAOCAQEA
        JSDcANsOFcfRyh/DGTftKLKLzjl6+YES91FMIHj+1M6nfxanoOXT/nF1FuhU1znU
        oj96MUuJEiq0AKxNO69V0dvv3b6pit1jKghXqXXMe2NuV5AA6745uXDCQ9ksxM3Q
        +YjAQXm6d425v1OWZHWyLc0qUQkvNPTFWp+TaILLDT33E8+HgdH4cMleQAim1twz
        e0NhM9viZxwJ+skvt+m85PbDjZA8pwJoZJyJCO7XADys48fRK06ZKucoPG2eKOQ6
        YTKza4jCTInEQU0NImVsOlDTD8KP0BYzzMOWc1mxWdI6I73LzIpExYgNT/C704eU
        ZyOujzUQnmrI9k1AGALdmA==
        -----END CERTIFICATE-----
  - mas_config_name: "inst1-jdbc-wsapp-inst1ws1-manage"
    mas_config_chart: ibm-jdbc-config
    mas_config_scope: wsapp
    mas_workspace_id: inst1ws1
    mas_application_id: manage
    mas_config_kind: "jdbccfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    jdbc_type: incluster-db2
    jdbc_instance_name: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#jdbc_instance_name>
    jdbc_instance_username: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/credentials#username>
    jdbc_instance_password: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/credentials#password>
    mas_config_dir:
    jdbc_connection_url: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#jdbc_connection_url>
    db2_dbname: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#db2_dbname>
    db2_namespace: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#db2_namespace>
    app_suite_jdbccfg_labels:
      mas.ibm.com/applicationId: "manage"
      mas.ibm.com/configScope: application
      mas.ibm.com/instanceId: "inst1"
    system_suite_jdbccfg_labels:
      mas.ibm.com/configScope: system
      mas.ibm.com/instanceId: "inst1"
    ws_suite_jdbccfg_labels:
      mas.ibm.com/configScope: workspace-application
      mas.ibm.com/instanceId: "inst1"
      mas.ibm.com/workspaceId: "inst1ws1"
    wsapp_suite_jdbccfg_labels:
      mas.ibm.com/applicationId: "manage"
      mas.ibm.com/configScope: workspace-application
      mas.ibm.com/instanceId: "inst1"
      mas.ibm.com/workspaceId: "inst1ws1"
    jdbc_ca_pem:
      crt: |-
        <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/jdbc/db2wh-inst1-manage/config#ca_b64 | base64decode>
  - mas_config_name: "inst1-mongo-system"
    mas_config_chart: ibm-mas-mongo-config
    mas_config_scope: system
    mas_workspace_id: inst1ws1
    mas_application_id:
    mas_config_kind: "mongocfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    username: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/mongo#username>
    password: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/mongo#password>
    config:
      hosts:
        - host: b2f53ae4-95eb-4971-b57c-8e07dbce04e3-0.c5kmhkid0ujpmrucb800.databases.appdomain.cloud
          port: 32250
        - host: b2f53ae4-95eb-4971-b57c-8e07dbce04e3-1.c5kmhkid0ujpmrucb800.databases.appdomain.cloud
          port: 32250
        - host: b2f53ae4-95eb-4971-b57c-8e07dbce04e3-2.c5kmhkid0ujpmrucb800.databases.appdomain.cloud
          port: 32250
      configDb: admin
      authMechanism: DEFAULT
      retryWrites: false
      credentials:
        secretName: "system-mongo-credentials"
    certificates:
      - alias: ca
        crt: |
          -----BEGIN CERTIFICATE-----
          MIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
          BAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy
          MTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq
          hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ
          Pr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5
          y+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK
          pwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf
          weovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA
          1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw
          TjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X
          Zo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
          AQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ
          lV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS
          qsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY
          doqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN
          i+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz
          +PQzp/B9cQmOO8dCe049Q3oaUA==
          -----END CERTIFICATE-----
  - mas_config_name: "inst1-sls-system"
    mas_config_chart: ibm-mas-sls-config
    mas_config_scope: system
    mas_workspace_id: inst1ws1
    mas_application_id:
    mas_config_kind: "slscfgs"
    mas_config_api_version: "config.mas.ibm.com"
    use_postdelete_hooks: true
    registration_key: <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/sls#registration_key>
    url: "https://sls.mas-inst1-sls.svc"
    ca:
      crt: |
        <path:arn:aws:secretsmanager:us-east-1:435377327995:secret:fyre-dev/masdemo1/inst1/sls#ca_b64 | base64decode>
